[package]
name = "monitor-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monitor-central = { path = "../monitor-central" }
sysinfo = "0.28.4"
